<?php

return [
    1 => [
        'id' => 1,
        'slug' => 'revitaglow-pro',
        'name' => 'RevitaGlow Pro™',
        'title' => "RevitaGlow Pro™ - Offrez à vos cheveux le soin qu'ils méritent",
        'description' => "Stimule la croissance des cheveux et réduit la chute.",
        'subtitle' => "Arrêtez la chute des cheveux et favorisez la repousse avec RevitaGlow Pro™ !",
        'price' => 54.99,
        'old_price' => 109.99,
        'stock' => 100,
        'hero_image' => '/assets/images/produit_image_1.png',
        'gallery' => [
            '/assets/images/produit_image_1.png',
            '/assets/images/produit_image_2.png',
            '/assets/images/produit_image_3.png',
            '/assets/images/produit_image_4.png',
            '/assets/images/produit_image_5.png',
            '/assets/images/produit_image_6.png',
            '/assets/images/produit_image_7.png',
            '/assets/images/produit_image_8.png',
        ],
        'colors' => [
            [
                'name' => 'Noir',
                'swatch' => '#000000',
                'image' => '/assets/images/produit_image_8.png',
            ],
            [
                'name' => 'Rouge',
                'swatch' => '#ef4444',
                'image' => '/assets/images/produit_image_7.png',
            ],
        ],
        'sizes' => [],
        'depths' => [],
        'benefits' => [
            'Réduit la chute des cheveux',
            'Renforce les racines',
            'Résultats visibles rapidement',
            'Massage bien-être à domicile',
            'Facile à utiliser & sans fil',
        ],
        'specs' => [
            'Lumière rouge 850 nm',
            '72 dents de massage',
            '3 modes : relax, frais, fort',
            'Recharge USB',
            'Boîtier ABS résistant',
        ],
    ],

    2 => [
        'id' => 2,
        'slug' => 'soutien-gorge-confort-incomparable',
        'name' => 'Soutien-Gorge Confort Incomparable™',
        'title' => 'Soutien-Gorge Push-Up Invisible',
        'description' => "Invisible, confortable et parfait pour toutes les morphologies.",
        'subtitle' => 'Soutien-Gorge Confort Incomparable™',
        'price' => 18.99,
        'old_price' => 34.99,
        'stock' => 100,
        'hero_image' => '/assets/images/image_produit_1.png',
        'gallery' => [
            '/assets/images/image_produit_1.png',
            '/assets/images/image_produit_2.png',
            '/assets/images/image_produit_3.png',
            '/assets/images/image_produit_4.png',
            '/assets/images/image_produit_5.png',
            '/assets/images/image_produit_6.png',
            '/assets/images/image_produit_7.png',
            '/assets/images/image_produit_8.png',
            '/assets/images/image_produit_9.png',
        ],
        'colors' => [
            [
                'name' => 'Beige',
                'swatch' => '#f5f5dc',
                'image' => '/assets/images/image_produit_6.png',
            ],
            [
                'name' => 'Noir',
                'swatch' => '#000000',
                'image' => '/assets/images/image_produit_7.png',
            ],
            [
                'name' => 'Rose',
                'swatch' => '#f9a8d4',
                'image' => '/assets/images/image_produit_8.png',
            ],
            [
                'name' => 'Bleu',
                'swatch' => '#60a5fa',
                'image' => '/assets/images/image_produit_9.png',
            ],
        ],
        'sizes' => ['32', '34', '36', '38', '40', '42', '44', '46', '48', '50'],
        'depths' => ['A', 'B', 'C', 'D'],
        'benefits' => [
            'Maintien parfait sans baleines',
            'Invisible sous tous les vêtements',
            'Améliore la posture',
            'Confort toute la journée',
            'Adapté à toutes les poitrines',
        ],
        'specs' => [
            'Matériaux : Nylon & Spandex',
            'Épaisseur : Ultra fin',
            'Lavable en machine',
        ],
    ],
];